// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Empty) Validate() error {
	return nil
}
func (this *ConnectRequest) Validate() error {
	return nil
}
func (this *DisconnectRequest) Validate() error {
	return nil
}
func (this *ReceiveMessageRequest) Validate() error {
	return nil
}
func (this *ReceiveMessageResponse) Validate() error {
	return nil
}
func (this *SendMessageRequest) Validate() error {
	return nil
}
